language: node_js
node_js:
- '4.6'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
before_script:
- npm install -g grunt-cli
env:
- CXX=g++-4.8
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: VCeG+5BArq+OyO/9EkjlqW2LwNANEziG4f6MlJb2DM6iidRtzpBqt7jcdpbtKua861Eh9+o12z8UatIhkUGyZLIpQ8HTDDtRww79Zl1vXP7kFlGxkiEeKuzE3yQRUppM/Lhh+DRmwK6dsoKD7Fvkag0dQth4TKYg5szRqL8ROgk=
  on:
    tags: true
    repo: noflo/noflo-canvas
